# Generated by Django 5.0.6 on 2024-05-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_study_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'notes', 'verbose_name_plural': 'notes'},
        ),
    ]
