# Generated by Django 5.0.6 on 2024-05-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_study_app', '0003_homework'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'homework', 'verbose_name_plural': 'homework'},
        ),
    ]
