# Generated by Django 5.0.6 on 2024-05-11 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_study_app', '0005_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'todo', 'verbose_name_plural': 'todo'},
        ),
    ]
