# Generated by Django 5.0.6 on 2024-05-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_study_app', '0006_alter_todo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
    ]
